### ISSUE TITLE
sometimes it will not cash when I use the watchdog

### ISSUE THREAD

**Issue by HolenZhou** [SalomonBrys/ANR-WatchDog#10]
I use the watchdog in my app, why sometime it will crash when anr, but sometimes the android os anr dialog will appear(then it will not crash)?
I just code it by the default way:   new ANRWatchDog().start();

**Comment by SalomonBrys** [comment]
That's very weird.
do you start the watchdog conditionally ?

**Comment by HolenZhou** [comment]
Actually no, sometimes it just doesn't crash the app.  I try it again today, use new code like this:
in the Application I init the watchdog:
new ANRWatchDog().setANRListener(
                new ANRListener() {
                    @Override
                    public void onAppNotResponding(ANRError error) {
                        if (!DebugUtil.isDebuggerConnected()) {
                            throw error;
                        }
                    }
                }).start();

Then I simulate an ANR in my MainActivity without debugger connected by "Thread.sleep(10000)", I still found it doesn't crash utils the ANR dialog appear, but just one time. I don't know the reason.

**Comment by SalomonBrys** [comment]
That should not happen.
I will investigate as soon as I get the time ;)

**Comment by johnjohndoe** [comment]
@HolenZhou If you wrap the code snippet in backticks (three before, three after) it will be formatted nicely and much more readable.

**Comment by flex5678** [comment]
when I use suggested :
```if (!BuildConfig.DEBUG) {
    new ANRWatchDog().start();
}``` I don't get a report to Acralyzer 
but if I use just :
``` new ANRWatchDog().start();```

I get the report. 
??

**Comment by SalomonBrys** [comment]
How do you launch the application ?

**Comment by SalomonBrys** [comment]
Can you test with `v1.2.0` ?

**Comment by SalomonBrys** [comment]
Closing, after 8 month without reply
