### ISSUE TITLE
iMac 

### ISSUE THREAD

**Issue by Baebizzle** [SalomonBrys/ANR-WatchDog#12]
how to put and iMac in safe mode with command prompt when it wont go pass recovery mode how can i get back to desktop

**Comment by ndahlquist** [comment]
@SalomonBrys: how do you find these people? Lol!

**Comment by Baebizzle** [comment]
WTF!!!SO FUNNY?AND WHAT KIND OF PEOPLE YOU REFERRING TO?

**Comment by SalomonBrys** [comment]
Does not concerns ANR-Watchdog.
Issue is spam.
