### ISSUE TITLE
ANR-WatchDog not works with Fabric(Crashlytics)

### ISSUE THREAD

**Issue by giaotuancse** [SalomonBrys/ANR-WatchDog#13]
Hello,
I've implemented WatchDog in my project. But it has some problem with Fabric.
I catched the error then sent ANR error to Fabric but it seem not work

		    new ANRWatchDog().setANRListener(new ANRWatchDog.ANRListener() {

				@Override
				public void onAppNotResponding(ANRError arg0) {
				       Crashlytics.getInstance().core.logException(arg0);
				}
		    }).start();

**Comment by SalomonBrys** [comment]
Can you test with the new version `1.2.0` ?
I've corrected an issue that impacted ACRA. Maybe it impacted Fabric as well ?

**Comment by giaotuancse** [comment]
Hi SalomonBrys,

I tested the new version and it works well. Thank you so much :)

**Comment by SalomonBrys** [comment]
Great :)
