### ISSUE TITLE
ANR-WatchDog not works with Bugsnag

### ISSUE THREAD

**Issue by ekstro** [SalomonBrys/ANR-WatchDog#21]
I'm not sure if the problem is with WatchDog or Bugsnag. We implemented WatchDog in our project but we have some problems with ANR errors - they aren't sent to Bugsnag, but with Fabric everything works correctly.

```
new ANRWatchDog().setANRListener(new ANRWatchDog.ANRListener() {
    @Override
    public void onAppNotResponding(final ANRError error) {
        Bugsnag.notify(error);
        throw error;
    }
}).start();
```

**Comment by SalomonBrys** [comment]
I don't see how it could be a bug on ANR-Watchdog's part.

If you find out anything, feel free to re-open the ticket.

Maybe the fact that you throw the error stops the application before it is sent to bugsnag ?
