### ISSUE TITLE
onAppNotResponding not working properly

### ISSUE THREAD

**Issue by aanshul16** [SalomonBrys/ANR-WatchDog#22]
Hi ,

As mentioned in doc about onAppNotResponding call back. 
It is said final user will not get **app not responding** dialog if we override this function.

But I used below code :- 
new ANRWatchDog().setReportMainThreadOnly().start();
            new ANRWatchDog().setANRListener(new ANRWatchDog.ANRListener() {
                @Override
                public void onAppNotResponding(ANRError error) {
                    if (!isDebuggerConnected()) {
                        throw error;
                    }
                }
            }).start();

And I am getting App Not responding dialog.

Kindly help me.

**Comment by SalomonBrys** [comment]
Hi,
you are creating two different watch dogs.
- One that reports only the main thread, but will throw the exception
- One that will get the exception in it's method.

You should create only one watchdog!

```java
new ANRWatchDog()
    .setReportMainThreadOnly()
    .setANRListener(new ANRWatchDog.ANRListener() {
        @Override
        public void onAppNotResponding(ANRError error) {
            if (!isDebuggerConnected()) {
                throw error;
            }
        }
    })
    .start()
;
```
