### ISSUE TITLE
Watchdog send error to Fabric (Crashlytics)

### ISSUE THREAD

**Issue by giaotuancse** [SalomonBrys/ANR-WatchDog#23]
Hello,
I implemented WathchDog in my project. Boot seem like it has problem with WatchDog version 1.0.3.
The logs were not send to Fabric although I catched the error . Please help me check it. 
Here's the code
       new ANRWatchDog().setANRListener(new ANRWatchDog.ANRListener() {
            @Override
            public void onAppNotResponding(ANRError arg0) {
                   Crashlytics.getInstance().core.logException(arg0);
            }
        }).start();

Thank you.

**Comment by SalomonBrys** [comment]
There is nothing wrong in your code.
The truth must be elsewhere...

**Comment by giaotuancse** [comment]
Can you help me a little check on your side?

**Comment by ndahlquist** [comment]
Have you tried testing (by printing via logcat) whether the `onAppNotResponding` callback is invoked? This would help to determine whether the issue is on the ANR-Watchdog side, or on the Crashlytics side.

**Comment by GajanandSwamy** [comment]
i used like this

 new ANRWatchDog().setANRListener(new ANRWatchDog.ANRListener() {
            @Override
            public void onAppNotResponding(ANRError error) {
                // Handle the error. For example, log it to HockeyApp:
                Intent intent = new Intent(MainActivity.this, SecondActivity.class);
                startActivity(intent);

            }
        }).start();


but app is crashing

**Comment by SalomonBrys** [comment]
Yep, that is intended.
This is a crash handler. Meaning that, when it is called, the app has ANR'd, the boat has sunk, it's too late.
Any interraction with the UI will not work as the UI thread is still not responding !

If you need to start a new activity, you can, but [in a new process](https://developer.android.com/guide/topics/manifest/activity-element.html#proc).

**Comment by GajanandSwamy** [comment]
sir how can i start new activity on ANR appears,,please give me code..and i
dont want to display ANR box as well
