### ISSUE TITLE
看了下你的源码，原理比较简单，但是还是有不准确的情况

### ISSUE THREAD

**Issue by SheepYoung** [SalomonBrys/ANR-WatchDog#24]
看了下你的源码，原理比较简单，但是还是有不准确的情况，因为你靠的就是UiHandler来实现你的目标代码是否响应了，来判断当前UI是否卡顿，表面上看是可信，只是粗略上的数据。实际上，这样做不仅多起了一个线程去Dispatch 一个消息，性能消耗了，而且不能准确的判断到底是那个函数耗时了（通过消息队列来判断，实际上有时间差，不够精准）！
   我觉得ANR监测的正确姿势还是要需要做AOP，这样才能准确的监控到每一个函数的调用时间，然后做精准的定位。
    目前aspectJ已经做的很好，做这个完全是一个非常方便的事情，可以慎重考虑一下~~

**Comment by SalomonBrys** [comment]
Sorry, I don't speak Chinese.

我不会说中文.

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SheepYoung** [comment]
My English is not good~~

I had saw your source code, the principle is simple and useful , but there are still not accurate enough. because you achieve your test code by Ui handler,   with your test code response to judge it whether has ANR.  it look like reliable, but it is  not accurate enoug. In the other hand, you take a thread to dispatch a message, performance is used, and using message queue has a time lag, it is not accurate enough.
I think you can use AOP, you can monitor to each function call time, and find the problem what it is.
AspectJ has been doing very well at present, you can think about it
