### ISSUE TITLE
watch for other applications being anred

### ISSUE THREAD

**Issue by ConductedClever** [SalomonBrys/ANR-WatchDog#26]
Hi. Is there any way to watch for other apps anr??? I mean for example I write an app called anrwatcher and it reports all the anrs from the all apps run through device. Thanks in advance.

**Comment by connyduck** [comment]
No.
There may be some way to do this on a rooted device, but definitely not with this library.

**Comment by SalomonBrys** [comment]
Nope, certainly not possible with this lib.

The only way to do this is to have an external app watch `/data/anr/traces.txt`, but you'd probably need root.
