### ISSUE TITLE
Thread timeout?

### ISSUE THREAD

**Issue by wisejoy7** [SalomonBrys/ANR-WatchDog#27]
Hey, this is a fantastic project and very useful indeed. I am using the below code for checking ANRs : 

` // ANR Reporting

        /*if (BuildConfig.DEBUG == false) {
            new ANRWatchDog(5000 *//*timeout*//*).start();
        }*/

        new ANRWatchDog().setIgnoreDebugger(true).start();

        // Prevent app termination
        new ANRWatchDog().setANRListener(new ANRWatchDog.ANRListener() {
            @Override
            public void onAppNotResponding(ANRError error) {
                // Handle the error. For example, log it to HockeyApp:
                Intent cu = new Intent(UriActivity.this, CrashActivity.class);
                if(error!=null) {
                    cu.putExtra("errorx", error.toString());
                }
                startActivity(cu);
            }
        }).start();

        // ANR Reporting End`

My questions are
1. Do I need to insert above code for every activity to check ANRs or launcher activity itself is enough? Meaning, does it have context only for the current activity or has context of all activities in the app.
Lets say I launch another activity other than the launcher activity using a service, then will I get ANR on that particular non launcher activity?  There can be a limit to number of parallel threads allowed on a particular android device that is why I wanted raise this question. Say I use above code in 5 activities, I will have 4 unnecessary parallel threads.  

2. Can I use it on any of my apps with commercial use? Is the license Open Source? 

Thanks!

**Comment by doubleo2** [comment]
1. You only need one watchdog per process. The simplest solution is to create the watchdog in a custom application class - you can see an example of this in the testapp folder
2. I can't tell you whether you can or cannot use it in your commercial app, but it is released under the MIT license. According to GNU, [the MIT license is GPL compatible](https://www.gnu.org/licenses/license-list.en.html) and qualifies as a "free software" license

**Comment by SalomonBrys** [comment]
Yep, thanks @doubleo2 :smile:
