### ISSUE TITLE
Few queries - Not exactly issue

### ISSUE THREAD

**Issue by AN319755** [SalomonBrys/ANR-WatchDog#35]
I am using both ANR-Watchdog and Dropbox to catch app's anr.
I am seeing below given cases:
1) When ANR-Watchdog is reporting the ANR at that time Dropbox is not having ANR entry.
2) When ever ANR-Watchdog misses to throw the exception, at that time we are having Dropbox entry.
3) very rarely we are seeing both Watchdog and Dropbox having same entries.

Could you please advice, which one of above should actually happen as per your experience?
Though i am seeing that ANRWatchdog is efficient than Dropbox. But because of watchdog missing few anr i had to introduce dropbox mechanism.

**Comment by SalomonBrys** [comment]
I have no idea how Dropbox works.
However, when ANR-Watchdog catches an ANR, if it is not handled, then the entire application crashes, which makes any other ANR looking library not see the ANR.
The same goes the other way around, when Dropbox catches it, then ANR-Watchdog cannot see it.
Both report happens on the rare case where both libraries are seeing the ANR at the exact same time.
