### ISSUE TITLE
Main thread is in runnable state but still ANR is detected.

### ISSUE THREAD

**Issue by kshitiz-dunzo** [SalomonBrys/ANR-WatchDog#55]
Hello,
We integrated your library and we are seeing some weird logs on our crashlytics, like below:

Caused by com.github.anrwatchdog.ANRError$$$_Thread
main (state = RUNNABLE)

The state is runnable but it still shows up as an ANR. Is this a false positive?

**Comment by SalomonBrys** [comment]
I don't think so.
ANRWatchDog works a very simple way : it schedules a "ticker" to be run on the UI thread ASAP, and waits 5 seconds to check if the ticker was ran. If it wasn't, it means that the UI thread is blocked (or more precisely, hasn't been able to run a posted Handler for 5 seconds).

There are multiple reasons the UI thread may be blocked and still in the RUNNABLE state : infinite loop, complex calculations, etc.

You should check the stack trace of the main thread, it should be an indication of what it was doing, and why it cannot run the ticker.
