### ISSUE TITLE
It's possible to make it work in debug mode too

### ISSUE THREAD

**Issue by TWiStErRob** [SalomonBrys/ANR-WatchDog#8]
Re [note](https://github.com/SalomonBrys/ANR-WatchDog#how-to-use-with-gradle--android-studio):
> Note that this will not enable the watchdog in debug mode, because the watchdog will prevent the debugger from hanging execution at breakpoints or exceptions (it will detect the debugging pause as an ANR).

You could easily work around this by checking [`android.os.Debug#isDebuggerConnected`](http://developer.android.com/reference/android/os/Debug.html#isDebuggerConnected()) whenever you detect an ANR and just ignore it.

Can you think of any reason not to do this by default?

**Comment by SalomonBrys** [comment]
ANR-Watchdog does not makes any check at startup. If you call `start()` on it, it will start.

That comment refers to the proposed usage in README:

    if (!BuildConfig.DEBUG) {
        new ANRWatchDog().start();
    }

If you still want the watchdog enabled in debug when the debugger is not connected, simply changes this for:

    if (!Debug,isDebuggerConnected()) {
        new ANRWatchDog().start();
    }

Be aware, however, that should you attach a debugger *after* startup, the watchdog will interpret debug pauses as ANRs.  
To prevent this, you could set an `ANRListener`:

    new ANRWatchDog().setANRListener(new ANRWatchDog.ANRListener() {
        @Override
        public void onAppNotResponding(ANRError error) {
            if (!Debug,isDebuggerConnected())
                throw error;
        }
    }).start();

**Comment by TWiStErRob** [comment]
Yep, I understand all that. I'm proposing to use the last code block (if-throw) in the core of the library so it's handled automatically for everyone by default without the need for configuration.

It would also simplify basic library usage to one code line and no caveats.

**Comment by SalomonBrys** [comment]
That's a good idea ;)

There would have to be an option to revert to previous behaviour.

I'll work on that ;)

**Comment by HolenZhou** [comment]
new ANRWatchDog().setANRListener(new ANRWatchDog.ANRListener() {
    @Override
    public void onAppNotResponding(ANRError error) {
        if (!Debug,isDebuggerConnected())
            throw error;
    }
}).start();

I think this code should be the basic use, it meets all requirements.

**Comment by HolenZhou** [comment]
I use the watchdog in my app, why sometime it will crash when anr,  but sometimes the android os anr dialog will appear(then it will not crash)?

**Comment by SalomonBrys** [comment]
Done in `1.2.0`.
Thanks for the report :)
